### PR TITLE
Update Vietnamese language and change language

### PR DESCRIPTION
**Pull request by phamnhatcn06**
OK..this is my new pull request. Can you setting up a new setting to change the default language for this extension. Thank so much.

### CODE REVIEW

**Comment by phamnhatcn06** [comment]
You don't mind about my commit into my git server.Because I deleted all and clone your project into my local and change only about language file.

**Comment by PendalF89** [comment]
You are once again sent a few other files in addition to the translation. 
"Can you setting up a new setting to change the default language for this extension"
- it can be in new versions.

**Comment by phamnhatcn06** [comment]
Sorry this is my mistake. You can merge now. Thank you.

**Comment by PendalF89** [comment]
Thank you a lot for translation! :+1:

**Pull request merged**
